# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=141)),
                ('usuario', models.CharField(max_length=25)),
                ('fecha_Publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(max_length=25)),
                ('fechaAmistad', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('archivo', models.FileField(upload_to='media/archivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MyPerfil',
            fields=[
                ('nombreUsuario', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='media/Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=25)),
                ('Decicion', models.IntegerField()),
                ('nombreContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioComenta', models.CharField(max_length=25)),
                ('usuarioComentado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioDescarga', models.CharField(max_length=25)),
                ('NombreDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_Publicacion', models.DateTimeField(auto_now_add=True)),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.MyPerfil')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='myperfil',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Sexo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.MyPerfil'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.MyPerfil'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Rol'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf.Publicacion'),
        ),
    ]
